# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import your libraries:
import numpy as np
import pandas as pd
%matplotlib inline

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html)).

In [2]:
# Your code here:
from sklearn.datasets import (make_classification, 
                              make_moons, 
                              make_circles,
                              load_diabetes)
diabetes_raw = load_diabetes()
diabetes_raw

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [3]:
diabetes_raw.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [4]:
diabetes_raw.values()

dict_values([array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]]), array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       1

Let's explore this variable by looking at the different attributes (keys) of `diabetes`. Note that the `load_diabetes` function does not return dataframes. It returns you a Python dictionary.

In [5]:
# Your code here:
#El -1 indica que la primera entrada de la dimencion es desconocida, por lo tanto crea n filas por 1 columna
diabetes_df = pd.DataFrame(data=np.hstack([diabetes_raw.data, diabetes_raw.target.reshape(-1,1)]),
                           columns=diabetes_raw.feature_names + ['target'])
diabetes_df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

#### The next step is to read the description of the dataset. 

Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable. Read the data description carefully to fully understand what each column represents.

*Hint: If your output is ill-formatted by displaying linebreaks as `\n`, it means you are not using the `print` function.*

In [6]:
# Your code here:
print(diabetes_raw.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bra

#### Based on the data description, answer the following questions:

1. How many attributes are there in the data? What do they mean?

1. What is the relation between `diabetes['data']` and `diabetes['target']`?

1. How many records are there in the data?

In [7]:
# Enter your answer here:
#¿Cuántos atributos hay en los datos? ¿Qué quieren decir?
print('¿Cuántos atributos hay en los datos?',\
      len(diabetes_raw.feature_names), '¿Qué quieren decir?')

#¿Cuál es la relación entre diabetes['data']y diabetes['target']?
#En base a la data se intenta predecir el progreso de la enfermedad

print('¿Cuántos registros hay en los datos?', diabetes_df.shape[0])

¿Cuántos atributos hay en los datos? 10 ¿Qué quieren decir?
¿Cuántos registros hay en los datos? 442


#### Now explore what are contained in the *data* portion as well as the *target* portion of `diabetes`. 

Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). Inspect the shape of `data` and `target`. Confirm they are consistent with the data description.

In [8]:
# Your code here:
print(diabetes_raw['data'].shape)
diabetes_raw['data']

(442, 10)


array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [9]:
print(diabetes_raw['target'].shape)
diabetes_raw['target']

(442,)


array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

# Challenge 2 - Perform Supervised Learning on the Dataset

The data have already been split to predictor (*data*) and response (*target*) variables. Given this information, we'll apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset.

#### Let's briefly revisit the linear regression formula:

```
y = β0 + β1X1 + β2X2 + ... + βnXn + ϵ
```

...where:

- X1-Xn: data 
- β0: intercept 
- β1-βn: coefficients 
- ϵ: error (cannot explained by model)
- y: target

Also take a look at the `sklearn.linear_model.LinearRegression` [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).

#### In the cell below, import the `linear_model` class from `sklearn`. 

In [10]:
# Your code here:
from sklearn.linear_model import LinearRegression

#### Next, let's split the training and test data.

Define `diabetes_data_train`, `diabetes_target_train`, `diabetes_data_test`, and `diabetes_target_test`. Use the last 20 records for the test data and the rest for the training data.

In [11]:
# Your code here:
from sklearn.model_selection import train_test_split
y=diabetes_raw['target']
X=diabetes_raw['data']
# Your code here:
diabetes_data_train, diabetes_data_test, diabetes_target_train, diabetes_target_test = train_test_split(X, y, test_size=20, random_state=42)

In [12]:
diabetes_target_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275.])

#### Create a new instance of the linear regression model and assign the new instance to the variable `diabetes_model`.

In [13]:
# Your code here:
diabetes_model = LinearRegression().fit(diabetes_data_train, diabetes_target_train)

In [14]:
predictions = diabetes_model.predict(X)
predictions

array([205.91235407,  70.51216117, 177.71854029, 164.89662997,
       129.48857594, 106.64057982,  72.57491094, 116.74537391,
       157.9400003 , 210.51374866,  97.26731987,  99.80035871,
       115.34218076, 161.63915014, 104.06093441, 175.05352092,
       210.13472516, 180.52214348, 148.56387895, 122.5251165 ,
       118.72718008,  85.37009905, 112.75759606, 249.09112244,
       167.59747934, 144.79182742,  96.90841546, 180.09510208,
       128.01114149, 181.44105242, 158.45255577,  68.1058754 ,
       268.65320896, 115.03873311,  80.18674601,  83.37439873,
       205.76622219, 156.74717093, 237.93242279, 132.8938715 ,
       149.34180742,  74.71858871, 144.79809046,  76.61234513,
       222.63313866, 124.1940387 , 142.20096214, 108.81236449,
        72.49766057, 189.22406168, 158.88731498, 170.1357838 ,
       132.82874345, 159.07058848, 138.89325448,  74.63535419,
       207.31467487,  82.43171442, 105.50735742, 129.17591569,
       115.60054716, 180.64608331,  61.79800683,  96.56

Fit the training data and target to `diabetes_model`. Print the *intercept* and *coefficients* of the model.

In [15]:
# Your code here:
diabetes_model.score(diabetes_data_train, diabetes_target_train)

0.514635629361752

In [16]:
diabetes_model.coef_

array([   0.87966595, -260.26800233,  536.46481603,  335.99923883,
       -835.78112685,  465.75770705,  136.19550049,  245.0609637 ,
        712.32643264,   64.48617517])

In [17]:
diabetes_model.intercept_

151.38210666917573

In [18]:
diabetes_model.predict(diabetes_data_test)

array([141.94686988, 176.31976585, 134.5341238 , 287.22045065,
       122.57807055,  96.46149132, 256.84813303, 184.79985601,
        92.90725729, 111.3887892 ,  98.52768466, 166.01352105,
        58.4586336 , 205.09969714, 100.7305117 , 130.33699952,
       218.46174455, 245.87678056, 192.99982451, 214.38094289])

#### Inspecting the results

From the outputs you should have seen:

- The intercept is a float number.
- The coefficients are an array containing 10 float numbers.

This is the linear regression model fitted to your training dataset.

#### Using your fitted linear regression model, predict the *y* of `diabetes_data_test`.

In [19]:
# Your code here:
diabetes_model.predict(diabetes_data_test)

array([141.94686988, 176.31976585, 134.5341238 , 287.22045065,
       122.57807055,  96.46149132, 256.84813303, 184.79985601,
        92.90725729, 111.3887892 ,  98.52768466, 166.01352105,
        58.4586336 , 205.09969714, 100.7305117 , 130.33699952,
       218.46174455, 245.87678056, 192.99982451, 214.38094289])

#### Print your `diabetes_target_test` and compare with the prediction. 

In [20]:
# Your code here:
diabetes_target_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275.])

In [21]:
diabetes_model.predict(diabetes_data_test)-diabetes_target_test

array([-77.05313012, 106.31976585, -67.4658762 ,  57.22045065,
        11.57807055,  12.46149132,  14.84813303, -87.20014399,
        -1.09274271,  15.3887892 ,   4.52768466, -85.98647895,
       -40.5413664 , -91.90030286, -34.2694883 ,  63.33699952,
       -76.53825545, -18.12321944,  22.99982451, -60.61905711])

#### Is `diabetes_target_test` exactly the same as the model prediction? Explain.

In [22]:
# Your explanation here:
#Desde el score se  veia que el modelo era malo
diabetes_model.score(diabetes_data_test, diabetes_target_test)

0.5049298620137603

# Bonus Challenge 1 - Hypothesis Testing with `statsmodels`

After generating the linear regression model from the dataset, you probably wonder: then what? What is the statistical way to know if my model is reliable or not?

Good question. We'll discuss that using Scikit-Learn in Challenge 5. But for now, let's use a fool-proof way by using the ([Linear Regression class of StatsModels](https://www.statsmodels.org/dev/regression.html)) which can also conduct linear regression analysis plus much more such as calcuating the F-score of the linear model as well as the standard errors and t-scores for each coefficient. The F-score and t-scores will tell you whether you can trust your linear model.

To understand the statistical meaning of conducting hypothesis testing (e.g. F-test, t-test) for slopes, read [this webpage](https://onlinecourses.science.psu.edu/stat501/node/297/) at your leisure time. We'll give you a brief overview next.

* The F-test of your linear model is to verify whether at least one of your coefficients is significantly different from zero. Translating that into the *null hypothesis* and *alternative hypothesis*, that is:

    ```
    H0 : β1 = β2 = ... = β10 = 0
    HA : At least one βj ≠ 0 (for j = 1, 2, ..., 10)
    ```

* The t-tests on each coefficient is to check whether the confidence interval for the variable contains zero. If the confidence interval contains zero, it means the null hypothesis for that variable is not rejected. In other words, this particular vaiable is not contributing to your linear model and you can remove it from your formula.

Read the documentations of [StatsModels Linear Regression](https://www.statsmodels.org/dev/regression.html) as well as its [`OLS` class](https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html) which stands for *ordinary least squares*.

#### In the next cell, analyze `diabetes_data_train` and `diabetes_target_train` with the linear regression model of `statsmodels`. Print the fit summary.

Your output should look like:

![statsmodels regression](../statsmodels.png)

In [23]:
# Your code here:
import statsmodels.api as sm
X = sm.add_constant(diabetes_data_train)

y = diabetes_target_train
model = sm.OLS(y, X).fit()
predictions = model.predict(X) 

print_model = model.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.515
Model:                            OLS   Adj. R-squared:                  0.503
Method:                 Least Squares   F-statistic:                     43.58
Date:                Thu, 22 Aug 2019   Prob (F-statistic):           1.71e-58
Time:                        20:29:55   Log-Likelihood:                -2276.8
No. Observations:                 422   AIC:                             4576.
Df Residuals:                     411   BIC:                             4620.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        151.3821      2.631     57.528      0.0

#### Interpreting hypothesis testing results

Answer the following questions in the cell below:

1. What is the F-score of your linear model and is the null hypothesis rejected?

1. Does any of the t-tests of the coefficients produce a confidence interval containing zero? What are they?

1. How will you modify your linear reguression model according to the test results above?

In [24]:
# Your answers here:
#1.71e-58

# Challenge 3 - Peform Supervised Learning on a Pandas Dataframe

Now that we have dealt with data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [25]:
# Your code here:
auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [26]:
# Your code here:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [27]:
# Your code here:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [28]:
# Your code here:
auto.model_year.max()

82

In [29]:
auto.model_year.min()

70

Check the dataset for missing values and remove all rows containing at least one missing value.

In [30]:
# Your code here:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [31]:
auto=auto.dropna()
auto.isna().sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [32]:
# Your code here:
auto.cylinders.value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

*Hint: To separate data for training and test, use the `train_test_split` method we used in previous labs.*

In [33]:
auto.head(1)

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"

In [34]:
# Your code here:
auto = auto.drop('car_name', axis=1)

In [35]:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year  
0          70  
1          70  
2          70  
3          70  
4          70

In [36]:
from sklearn.model_selection import train_test_split
y=auto.mpg
X=auto.drop('mpg', axis=1)
# Your code here:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Now we will processed and peform linear regression on this data to predict the mpg for each vehicle. 

#### In the next cell, create an instance of the linear regression model and call it `auto_model`. Fit `auto_model` with your training data.

In [37]:
# Your code here:
import statsmodels.api as sm
X = sm.add_constant(X_train)
y = y_train

auto_model = sm.OLS(y, X).fit()
predictions = auto_model.predict(X) 

print_model = auto_model.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.811
Model:                            OLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     218.4
Date:                Thu, 22 Aug 2019   Prob (F-statistic):          1.96e-107
Time:                        20:29:55   Log-Likelihood:                -832.28
No. Observations:                 313   AIC:                             1679.
Df Residuals:                     306   BIC:                             1705.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const          -15.0578      5.571     -2.703   

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


# Challenge 4 - Evaluate the Model

In addition to evaluating your model with F-test and t-test, you can also use the *Coefficient of Determination* (a.k.a. *r squared score*). This method does not simply tell *yes* or *no* about the model fit but instead indicates how much variation can be explained by the model. Based on the r squared score, you can decide whether to improve your model in order to obtain a better fit.

You can learn about the r squared score [here](). Its formula is:

![R Squared](../r-squared.png)

...where:

* yi is an actual data point.
* ŷi is the corresponding data point on the estimated regression line.

By adding the squares of the difference between all yi-ŷi pairs, we have a measure called SSE (*error sum of squares*) which is an application of the r squared score to indicate the extent to which the estimated regression model is different from the actual data. And we attribute that difference to the random error that is unavoidable in the real world. Obviously, we want the SSE value to be as small as possible.

#### In the next cell, compute the predicted *y* based on `X_train` and call it `y_pred`. Then calcualte the r squared score between `y_pred` and `y_train` which indicates how well the estimated regression model fits the training data.

*Hint: r squared score can be calculated using `sklearn.metrics.r2_score` ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html)).*

In [38]:
# Your code here:
from sklearn.metrics import r2_score
r2_score( y,predictions)

0.8107227953093896

#### Our next step is to evaluate the model using the test data. 

We would like to ensure that our model is not overfitting the data. This means that our model was made to fit too closely to the training data by being overly complex. If a model is overfitted, it is not generalizable to data outside the training data. In that case, we need to reduce the complexity of the model by removing certain features (variables).

In the cell below, use the model to generate the predicted values for the test data and assign them to `y_test_pred`. Compute the r squared score of the predicted `y_test_pred` and the oberserved `y_test` data.

In [39]:
# Your code here:
y_test_pred = auto_model.predict(sm.add_constant(X_test))
r2_score( y_test,y_test_pred)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


0.7942349075428576

#### Explaining the results

The r squared scores of the training data and the test data are pretty close (0.8146 vs 0.7818). This means our model is not overfitted. However, there is still room to improve the model fit. Move on to the next challenge.

# Challenge 5 - Improve the Model Fit

While the most common way to improve the fit of a model is by using [regularization](https://datanice.github.io/machine-learning-101-what-is-regularization-interactive.html), there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [40]:
# Your code here:
from sklearn.model_selection import train_test_split
y=auto.mpg
X=auto.drop('mpg', axis=1)
# Your code here:
X_train09, X_test09, y_train09, y_test09 = train_test_split(X, y, test_size=0.1, random_state=42)

Initialize a new linear regression model. Name this model `auto_model09`. Fit the model to the new sample (training) data.

In [41]:
# Your code here:
import statsmodels.api as sm
X = sm.add_constant(X_train)
y = y_train

auto_model09 = sm.OLS(y, X).fit()
predictions = auto_model09.predict(X) 

print_model = auto_model09.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.811
Model:                            OLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     218.4
Date:                Thu, 22 Aug 2019   Prob (F-statistic):          1.96e-107
Time:                        20:29:56   Log-Likelihood:                -832.28
No. Observations:                 313   AIC:                             1679.
Df Residuals:                     306   BIC:                             1705.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const          -15.0578      5.571     -2.703   

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


Compute the predicted values and r squared score for our new model and new sample data.

In [42]:
# Your code here:
r2_score( y,predictions)

0.8107227953093896

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [43]:
# Your code here:
y_test_pred = auto_model.predict(sm.add_constant(X_test09))
r2_score( y_test09,y_test_pred)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


0.8440571020562723

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [44]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [45]:
# Your code here:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

estimator = SVR(kernel="linear")
selector = RFE(estimator=estimator, n_features_to_select=3, step=1)
selector = selector.fit(X, y)
selector.support_

array([False,  True, False, False, False,  True,  True])

Fit the model and print the ranking

In [46]:
# Your code here:
selector.ranking_

array([5, 1, 2, 3, 4, 1, 1])

In [47]:
X.head()

const  cylinders  displacement  horse_power  weight  acceleration  \
260    1.0          6         225.0        110.0    3620          18.7   
184    1.0          4         140.0         92.0    2572          14.9   
174    1.0          6         171.0         97.0    2984          14.5   
64     1.0          8         318.0        150.0    4135          13.5   
344    1.0          4          86.0         64.0    1875          16.4   

     model_year  
260          78  
184          76  
174          75  
64           72  
344          81

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [57]:
# Your code here:
from sklearn.model_selection import train_test_split
y=auto.mpg
X=auto.drop(['displacement', 'horse_power', 'weight'], axis=1)
# Your code here:
X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = train_test_split(X, y, test_size=0.1, random_state=42)

In [59]:
X_train_reduced.head()

mpg  cylinders  acceleration  model_year
73   13.0          8          14.0          72
147  24.0          4          15.5          74
375  36.0          4          15.3          82
143  26.0          4          14.5          74
159  14.0          8          13.5          75

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [60]:
# Your code here: 
import statsmodels.api as sm
X = sm.add_constant(X_train_reduced)
y = y_train_reduced

auto_model_reduced = sm.OLS(y, X).fit()
predictions = auto_model_reduced.predict(X) 

print_model = auto_model_reduced.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.200e+30
Date:                Thu, 22 Aug 2019   Prob (F-statistic):               0.00
Time:                        20:34:26   Log-Likelihood:                 10402.
No. Observations:                 352   AIC:                        -2.079e+04
Df Residuals:                     347   BIC:                        -2.077e+04
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const        -6.928e-14   4.65e-14     -1.490   

In [61]:
r2_score( y,predictions)

1.0

#### Conclusion

You may obtain the impression from this lab that without knowing statistical methods in depth, it is difficult to make major progress in machine learning. That is correct. If you are motivated to become a data scientist, statistics is the subject you must be proficient in and there is no shortcut. 

Completing these labs is not likely to make you a data scientist. But you will have a good sense about what are there in machine learning and what are good for you. In your future career, you can choose one of the three tracks:

* Data scientists who need to be proficient in statistical methods.

* Data engineers who need to be good at programming.

* Data integration specialists who are business or content experts but also understand data and programming. This cross-disciplinary track brings together data, technology, and business and will be in high demands in the next decade.